### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jianbiaoli** [1dayac/Novel-X#1]
Hi,

I keep getting the following error messages:
RuleException:
CalledProcessError in line 73 of /zfssz2/novelx_20200221/HBFY-22/Snakefile:
Command ' set -euo pipefail;
        /hwfssz5/software/Novel-X/bamtofastq  unmapped_bam/phased_possorted_bam.bam temp_reads_phased_possorted_bam
        /ldfssz1/software/longranger2.2.2/longranger-2.2.2/longranger basic --id reads --fastqs temp_reads_phased_possorted_bam/*
        mv reads/outs/barcoded.fastq.gz reads/phased_possorted_bam.fastq.gz
        gunzip reads/phased_possorted_bam.fastq.gz ' returned non-zero exit status 64.
  File "/zfssz2/novelx_20200221/HBFY-22/Snakefile", line 73, in __rule_convert_unmapped_bam_to_fastq
  File "/hwfssz5/software/python3.6.9/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job convert_unmapped_bam_to_fastq since they might be corrupted:
temp_reads_phased_possorted_bam
Skipped removing non-empty directory temp_reads_phased_possorted_bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

I couldn't figure out how to solve this problem. Could you help me with that?

Thank you!

Jianbiao Li

**Comment by 1dayac** [comment]
Hello Jianbiao,

Sure, I will be happy to help.

Could you please run the following commands one by one, so I will be able to see an exact error message and command that causes it.

/hwfssz5/software/Novel-X/bamtofastq unmapped_bam/phased_possorted_bam.bam temp_reads_phased_possorted_bam
/ldfssz1/software/longranger2.2.2/longranger-2.2.2/longranger basic --id reads --fastqs temp_reads_phased_possorted_bam/*
mv reads/outs/barcoded.fastq.gz reads/phased_possorted_bam.fastq.gz
gunzip reads/phased_possorted_bam.fastq.gz
 

I suppose, that you need to add --lr20 flag to bamtofastq command, but lets check first.

**Comment by jianbiaoli** [comment]
Thank you very much for your quick reply and your help. Here are the output messages after executing the above-mentioned commands.

`$ /hwfssz5/software/Novel-X/bamtofastq  unmapped_bam/phased_possorted_bam.bam temp_reads_phased_possorted_bam`
`bamtofastq v1.0.0`
`Args { arg_bam: "unmapped_bam/phased_possorted_bam.bam", arg_output_path:`
`"temp_reads_phased_possorted_bam", flag_locus: None, flag_reads_per_fastq: 50000000, flag_gemcode: false, flag_lr20: false, flag_cr11: false }`
`Writing finished.  Observed 42653764 unique read ids. Wrote 42653764 read pairs (0 cached)`

`$ /ldfssz1/software/longranger2.2.2/longranger-2.2.2/longranger basic --id reads --fastqs temp_reads_phased_possorted_bam/*`
`longranger basic (2.2.2)`
`Copyright (c) 2018 10x Genomics, Inc.  All rights reserved.`
`-------------------------------------------------------------------------------`
`Usage:`
`    basic`
`        --id=ID`
`        --fastqs=PATH`
`        [--sample=PREFIX]`
`        [options]`
`    basic <run_id> <mro> [options]`
`    basic -h | --help | --version`

It seems the longranger command line option --fastqs has wrong value. There are two folders under the temp_reads_phased_possorted_bam which showed below.

`$ ls temp_reads_phased_possorted_bam/`
`HBFY-22_LibraryNotSpecified_1_unknown_fc HBFY-22_LibraryNotSpecified_2_unknown_fc`

This error may be because of the input bam file was got from multi-library mode of Longranger pepline. Any ideas to solve this problem?

Best wishes,
Jianbiao Li

**Comment by 1dayac** [comment]
Ok, I see. I didn't anticipate that BAM file can contain multiple libraries. 
Is this dataset public? It would be very convenient to test on it.
I think I will come up with the solution by Monday and write to this thread

**Comment by jianbiaoli** [comment]
Sorry, we can not make this dataset publicly available yet. Looking foward to seeing solutions. Thank you!

Best regards,
Jianbiao Li

**Comment by 1dayac** [comment]
Because of COVID paandemy, I can't work productively, but hoe to came up with solution soon. Sorry about that!

**Comment by jianbiaoli** [comment]
Take care! Quarantine is an effective way to protect yourself. Please let me know if you need any help.

Best wishes,
Jianbiao Li

**Comment by 1dayac** [comment]
Hi @Jianbiaoli !

I think I was able to fix this issue.
The last commit in the master branch (116cf5a) addresses it. 
Let me know if it works for you!

Take care!
Dmitry

**Comment by jianbiaoli** [comment]
Hi  @1dayac 

Thank you so much for your help! It works now.
