### ISSUE TITLE
Velvet MAXKMERLENGTH parameter

### ISSUE THREAD

**Issue by morispi** [1dayac/Novel-X#2]
Hi,

Not much of an issue, but Novel-X seems to be using k-mers of size >31, which is not allowed by default with Velvet.
This needs to be specified at Velvet compilation, eg with `make 'MAXKMERLENGTH=100'`

Correct me if I'm wrong, but I don't think you mentioned this in your README / requirements?
I thus used my default installation of velvet, and ended up with errors, and unable to run Novel-X. After recompiling Velvet with the correct parameters, all worked well.

Maybe it could be worth adding this somewhere? This could avoid your users some troubles if they're not aware of that Velvet limitation. :)

Best,
Pierre

**Comment by 1dayac** [comment]
Hello Pierre,

Yes, you are completely right!
I will correct the manual ASAP!

Thanks!

**Comment by 1dayac** [comment]
Manual is fixed now,
thanks again!
