### ISSUE TITLE
Error from --lr20 flag

### ISSUE THREAD

**Issue by anderswe** [1dayac/Novel-X#6]
Hi Dmitry,

Super grateful for your work with Novel-X, really excited to try it on some in-house data.

I'm running into an issue with those data, which are from 10X Linked-Reads and were aligned with ```longranger align``` from Long Ranger v2.2.2 --> it appears to be related to the --lr20 flag in my call to ```novel-x.py run```. Here is the error:

```
[Mon Dec  5 05:40:47 2022]
rule convert_unmapped_bam_to_fastq:
    input: unmapped_bam/possorted_bam.bam
    output: temp_reads_possorted_bam
    jobid: 13
    wildcards: sample=possorted_bam
    resources: tmpdir=/localhd/715736

bamtofastq v1.0.0
error: Do not use a pipeline-specific command-line flag: --lr20. Supplied BAM file already contains bamtofastq headers.
[Mon Dec  5 05:40:48 2022]
Error in rule convert_unmapped_bam_to_fastq:
    jobid: 13
    output: temp_reads_possorted_bam
    shell:
        
        /path/to/Novel-X/bamtofastq --lr20 unmapped_bam/possorted_bam.bam temp_reads_possorted_bam
        
```

Omitting the --lr20 flag allows Novel-X to run to completion, I just don't know how much the results are distorted from this. Perhaps this is from using ```.bam``` files aligned with Long Ranger 2.2 and not 2.0?

Thank you for your help!
Anders

**Comment by 1dayac** [comment]
Hello Anders,

You don't need the --lr20 flag, if you used Longranger v.2.2.2 to align reads.
The problem is that the 10X Genomics provided bamtofastq program requires this flag, you Longrager V2.0 was used.
This flag affects only bamtofastq program and nothing else
Results should not be distorted

Dmitry

**Comment by anderswe** [comment]
Fantastic! Thanks for the helpful and superfast reply, Dmitry
